blank_issues_enabled: false

contact_links:
  - name: General question
    url: https://github.com/vacanza/python-holidays/discussions/new?category=q-a
    about: Ask a question

  - name: Bug Report
    url: https://github.com/vacanza/python-holidays/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md
    about: Report a bug

  - name: Feature Request
    url: https://github.com/vacanza/python-holidays/blob/dev/.github/ISSUE_TEMPLATE/feature_request.md
    about: Suggest an idea
